### ISSUE TITLE
new ui feature: WYSIWYG block editor with Editor.js

### ISSUE THREAD

**Issue by ap0nia** [CloudCodesStuff/magenta-notes-app#13]
# Summary
Implement a WYSIWYG text editor using [Editor.js](Library Reference: https://editorjs.io/)

This is an advanced task that intends to mimic the text editor offered by Confluence in their workspaces.

But it's actually medium difficulty with a reference: https://github.com/shadcn-ui/taxonomy/blob/main/components/editor.tsx

## Files changed
- `src/lib/hooks/editor.ts`
- `src/pages/editor/index.tsx`

## Tasks
- [ ] Create the necessary files
- [ ] Integrate Editor.js into React with a custom hook
- [ ] Create a React component that will render the editor onto the page

## Samples
```tsx
// src/lib/hooks/editor.ts
import EditorJS from '@editorjs/editorjs';

/**
 * React hook that initializes EditorJS.
 */
export function useEditor() { ... }

// src/pages/editor/index.tsx
import { useEditor } from '@/lib/hooks/editor'

export default function Editor() {
  const editor = useEditor()
 // ...
}
```

# More Info
WYSIWYG = what you see is what you get
